spring:
  application:
    name: "googel-gen-ai-spring"
ai:
  api-key: ${GOOGLE_API_KEY:missing_key}
  model: gemini-3.1-flash-lite-preview # 3.1-flash-lite-preview가 안될 경우를 대비해 안정 버전 권장
  default-system: "너는 20년 경력의 시니어 개발자야. 친절하고 간결하게 대답해줘."
